version: "3.9"
services:
  db:
    image: mariadb:latest
    container_name: m183-lb2-db
    expose:
      - "3306"
    environment:
      - MARIADB_ROOT_PASSWORD=Some.Real.Secr3t

  web:
    image: node:latest
    user: "node"
    working_dir: /home/node/app
    container_name: m183-lb2-web
    environment:
      - DBSERVER=m183-lb2-db
      - NODE_ENV=production
    ports:
      - "80:3000"
    volumes:
      - type: bind
        source: ..
        target: /home/node/app
    command: "npm start"
    depends_on:
      - db